// <auto-generated />
using System;
using DeveloperInfo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperInfo.Infrastructure.Migrations
{
    [DbContext(typeof(DevelopersContext))]
    partial class DevelopersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperInfo.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("DeveloperInfo.Models.DeveloperSocialNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SocialNetworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("SocialNetworkId");

                    b.ToTable("DeveloperSocialNetworks");
                });

            modelBuilder.Entity("DeveloperInfo.Models.DeveloperTechnology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("DeveloperTechnology");
                });

            modelBuilder.Entity("DeveloperInfo.Models.SocialNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SocialNetworks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("415fdd0c-670a-41e4-8feb-996e55c06825"),
                            Name = "github"
                        },
                        new
                        {
                            Id = new Guid("5a9c90a4-970c-4379-b0ca-6b2e32f2b39f"),
                            Name = "facebook"
                        },
                        new
                        {
                            Id = new Guid("5c4fea1c-ffd8-466f-bc59-877169af3f0e"),
                            Name = "instagram"
                        },
                        new
                        {
                            Id = new Guid("e1aadc92-4845-44cc-a6aa-ad482dcc4604"),
                            Name = "linked_in"
                        },
                        new
                        {
                            Id = new Guid("c6c7569f-efd7-405b-8534-716ed0b15747"),
                            Name = "telegram"
                        },
                        new
                        {
                            Id = new Guid("f1b00491-6418-4cf9-9bd1-f387f59e9eeb"),
                            Name = "twitter"
                        },
                        new
                        {
                            Id = new Guid("07cbeefd-bcb7-4d31-ad5c-ad6286a4818e"),
                            Name = "whatsapp"
                        });
                });

            modelBuilder.Entity("DeveloperInfo.Models.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96ebddf2-a988-4bd8-8657-019153518c10"),
                            Name = "python"
                        },
                        new
                        {
                            Id = new Guid("1d02fef3-1234-4123-9fdb-0786e1a2577c"),
                            Name = "java"
                        },
                        new
                        {
                            Id = new Guid("9be041ea-84e5-4dbc-afa9-adfa650ba67f"),
                            Name = "net"
                        },
                        new
                        {
                            Id = new Guid("1d32c8dd-e678-4c2b-84f0-ebf4be54d2c9"),
                            Name = "javascript"
                        },
                        new
                        {
                            Id = new Guid("1950191e-4dd7-4eae-b9a5-627de1374a0a"),
                            Name = "c_sharp"
                        },
                        new
                        {
                            Id = new Guid("935faf7d-9775-4952-9a3c-b2dd71227e26"),
                            Name = "php"
                        },
                        new
                        {
                            Id = new Guid("bb453778-eaa9-4974-98be-b844fa49337f"),
                            Name = "c_c_plusplus"
                        },
                        new
                        {
                            Id = new Guid("c5e1a897-459a-48d1-a11e-12218b1f7dc5"),
                            Name = "typescript"
                        },
                        new
                        {
                            Id = new Guid("3602404d-9383-4940-84bc-39abbf6c5f1b"),
                            Name = "nodejs"
                        },
                        new
                        {
                            Id = new Guid("7cfb814a-e3e1-45d5-a0e7-da32c1ff02ed"),
                            Name = "dart"
                        },
                        new
                        {
                            Id = new Guid("c27806d4-6554-45d5-8f8f-1a1a37cf3913"),
                            Name = "swift"
                        },
                        new
                        {
                            Id = new Guid("e81b307d-6f42-4a52-8d17-38cd1885e18a"),
                            Name = "objective_c"
                        },
                        new
                        {
                            Id = new Guid("3321884d-56c8-448e-b75f-79ad57cc132a"),
                            Name = "django"
                        },
                        new
                        {
                            Id = new Guid("e885dc48-a075-45d1-8c5c-682d40c242fe"),
                            Name = "spring"
                        },
                        new
                        {
                            Id = new Guid("ab6d3278-7934-4b60-8eb5-f7b7d8e578a4"),
                            Name = "laravel"
                        },
                        new
                        {
                            Id = new Guid("c1afea03-a210-4a19-872e-97aeae89ec10"),
                            Name = "react"
                        },
                        new
                        {
                            Id = new Guid("ebeec377-39fc-447f-b791-caa4a55254f6"),
                            Name = "angular"
                        },
                        new
                        {
                            Id = new Guid("31742697-8d3c-4803-9fc8-16ae6764e070"),
                            Name = "blazor"
                        },
                        new
                        {
                            Id = new Guid("0f466aab-935c-4ddb-a1da-76e7008ef6f5"),
                            Name = "vuejs"
                        },
                        new
                        {
                            Id = new Guid("e79efe58-0efc-4d96-b0d4-5ec6aaed9911"),
                            Name = "nestjs"
                        },
                        new
                        {
                            Id = new Guid("a383d62f-b7dc-47e4-8553-c22374a2bd91"),
                            Name = "adonisjs"
                        },
                        new
                        {
                            Id = new Guid("58b2bf1a-b49c-4784-addb-ef86289ae2d4"),
                            Name = "flutter"
                        },
                        new
                        {
                            Id = new Guid("da7c0c08-bb63-4bf0-ac11-f31b895c76fc"),
                            Name = "ionic"
                        });
                });

            modelBuilder.Entity("DeveloperInfo.Models.DeveloperSocialNetwork", b =>
                {
                    b.HasOne("DeveloperInfo.Models.Developer", "Developer")
                        .WithMany("SocialNetworks")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeveloperInfo.Models.SocialNetwork", "SocialNetwork")
                        .WithMany()
                        .HasForeignKey("SocialNetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("SocialNetwork");
                });

            modelBuilder.Entity("DeveloperInfo.Models.DeveloperTechnology", b =>
                {
                    b.HasOne("DeveloperInfo.Models.Developer", "Developer")
                        .WithMany("Technologies")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeveloperInfo.Models.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("DeveloperInfo.Models.Developer", b =>
                {
                    b.Navigation("SocialNetworks");

                    b.Navigation("Technologies");
                });
#pragma warning restore 612, 618
        }
    }
}
